/*
 * CardPay REST API
 * The CardPay API uses HTTP verbs and a RESTful endpoint structure. Request and response payloads are formatted as JSON.
 *
 * OpenAPI spec version: 3.0
 * Contact: support@cardpay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Billing is the customer’s billing address. Depending on account settings Billing may be required. An element structure is identical to shipping address element. Billing fields are required if &#x60;billing_address&#x60; is presented. For BANKCARD payment method only.
 */
@ApiModel(description = "Billing is the customer’s billing address. Depending on account settings Billing may be required. An element structure is identical to shipping address element. Billing fields are required if `billing_address` is presented. For BANKCARD payment method only.")

public class BillingAddress {
  @SerializedName("city")
  private String city = null;

  @SerializedName("country")
  private String country = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("street")
  private String street = null;

  @SerializedName("zip")
  private String zip = null;

  public BillingAddress city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Billing city. May include whitespaces, hyphens, apostrophes, commas and dots
   * @return city
  **/
  @ApiModelProperty(required = true, value = "Billing city. May include whitespaces, hyphens, apostrophes, commas and dots")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public BillingAddress country(String country) {
    this.country = country;
    return this;
  }

   /**
   * [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) code of billing country: 2 or 3 latin letters or numeric code 
   * @return country
  **/
  @ApiModelProperty(example = "USA", required = true, value = "[ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) code of billing country: 2 or 3 latin letters or numeric code ")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public BillingAddress phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Valid customer phone number
   * @return phone
  **/
  @ApiModelProperty(required = true, value = "Valid customer phone number")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public BillingAddress state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Billing state or province. May include whitespaces, hyphens, apostrophes, commas and dots
   * @return state
  **/
  @ApiModelProperty(example = "NY", value = "Billing state or province. May include whitespaces, hyphens, apostrophes, commas and dots")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public BillingAddress street(String street) {
    this.street = street;
    return this;
  }

   /**
   * Billing street address. May include whitespaces, hyphens, apostrophes, commas, quotes, dots, slashes and semicolons
   * @return street
  **/
  @ApiModelProperty(required = true, value = "Billing street address. May include whitespaces, hyphens, apostrophes, commas, quotes, dots, slashes and semicolons")
  public String getStreet() {
    return street;
  }

  public void setStreet(String street) {
    this.street = street;
  }

  public BillingAddress zip(String zip) {
    this.zip = zip;
    return this;
  }

   /**
   * Billing postal code
   * @return zip
  **/
  @ApiModelProperty(required = true, value = "Billing postal code")
  public String getZip() {
    return zip;
  }

  public void setZip(String zip) {
    this.zip = zip;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillingAddress billingAddress = (BillingAddress) o;
    return Objects.equals(this.city, billingAddress.city) &&
        Objects.equals(this.country, billingAddress.country) &&
        Objects.equals(this.phone, billingAddress.phone) &&
        Objects.equals(this.state, billingAddress.state) &&
        Objects.equals(this.street, billingAddress.street) &&
        Objects.equals(this.zip, billingAddress.zip);
  }

  @Override
  public int hashCode() {
    return Objects.hash(city, country, phone, state, street, zip);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillingAddress {\n");
    
    if (city != null) sb.append("    city: ").append(toIndentedString(city)).append("\n");
    if (country != null) sb.append("    country: ").append(toIndentedString(country)).append("\n");
    if (phone != null) sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    if (state != null) sb.append("    state: ").append(toIndentedString(state)).append("\n");
    if (street != null) sb.append("    street: ").append(toIndentedString(street)).append("\n");
    if (zip != null) sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

