/*
 * CardPay REST API
 * The CardPay API uses HTTP verbs and a RESTful endpoint structure. Request and response payloads are formatted as JSON.
 *
 * OpenAPI spec version: 3.0
 * Contact: support@cardpay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Card Token feature (see &#x60;generate_token&#x60; field below) is almost the same as Recurring, but the difference is that in this case each payment is made with Cardholder presence and requires CVV2/CVC2/CAV2 (Secure code) and 3-D Secure if available. You can obtain Card Token by a sending usual transaction with the attribute &#x60;generate_token&#x60; having a value &#x60;true&#x60; in it. The generated Card Token is sent in a callback and response to GET request for early created transaction and only if created payment with &#x60;generate_token&#x60; attribute was successful. Each time when a token is requested, the new one is generated even for the same card. To use Card Token you can send it in &#x60;card_account.token&#x60; attribute, so a customer will not have to enter card details again, only CVV2/CVC2/CAV2 (Secure code) and pass 3-D Secure if needed. A Card Token cannot be used more than 1 year after the token was generated. Relates to PaymentRequest
 */
@ApiModel(description = "Card Token feature (see `generate_token` field below) is almost the same as Recurring, but the difference is that in this case each payment is made with Cardholder presence and requires CVV2/CVC2/CAV2 (Secure code) and 3-D Secure if available. You can obtain Card Token by a sending usual transaction with the attribute `generate_token` having a value `true` in it. The generated Card Token is sent in a callback and response to GET request for early created transaction and only if created payment with `generate_token` attribute was successful. Each time when a token is requested, the new one is generated even for the same card. To use Card Token you can send it in `card_account.token` attribute, so a customer will not have to enter card details again, only CVV2/CVC2/CAV2 (Secure code) and pass 3-D Secure if needed. A Card Token cannot be used more than 1 year after the token was generated. Relates to PaymentRequest")

public class PaymentData {
  @SerializedName("amount")
  private BigDecimal amount = null;

  @SerializedName("auth_code")
  private String authCode = null;

  @SerializedName("authentication_request")
  private Boolean authenticationRequest = null;

  @SerializedName("created")
  private String created = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("decline_code")
  private String declineCode = null;

  @SerializedName("decline_reason")
  private String declineReason = null;

  @SerializedName("dynamic_descriptor")
  private String dynamicDescriptor = null;

  @SerializedName("generate_token")
  private Boolean generateToken = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("is_3d")
  private Boolean is3d = null;

  @SerializedName("note")
  private String note = null;

  @SerializedName("preauth")
  private Boolean preauth = null;

  @SerializedName("rrn")
  private String rrn = null;

  /**
   * Current payment status, *(mandatory for WEBMONEY and BITCOIN payment method only)*
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    NEW("NEW"),
    
    IN_PROGRESS("IN_PROGRESS"),
    
    DECLINED("DECLINED"),
    
    AUTHORIZED("AUTHORIZED"),
    
    COMPLETED("COMPLETED"),
    
    CANCELLED("CANCELLED"),
    
    REFUNDED("REFUNDED"),
    
    PARTIALLY_REFUNDED("PARTIALLY_REFUNDED"),
    
    VOIDED("VOIDED"),
    
    CHARGED_BACK("CHARGED_BACK"),
    
    CHARGEBACK_RESOLVED("CHARGEBACK_RESOLVED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  public PaymentData amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * The total transaction amount in selected currency with dot as a decimal separator, must be less than 100 millions
   * @return amount
  **/
  @ApiModelProperty(required = true, value = "The total transaction amount in selected currency with dot as a decimal separator, must be less than 100 millions")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public PaymentData authCode(String authCode) {
    this.authCode = authCode;
    return this;
  }

   /**
   * Authorization code, provided by bank *(for BANKCARD payment method only)*
   * @return authCode
  **/
  @ApiModelProperty(value = "Authorization code, provided by bank *(for BANKCARD payment method only)*")
  public String getAuthCode() {
    return authCode;
  }

  public void setAuthCode(String authCode) {
    this.authCode = authCode;
  }

  public PaymentData authenticationRequest(Boolean authenticationRequest) {
    this.authenticationRequest = authenticationRequest;
    return this;
  }

   /**
   * If set to &#x60;true&#x60;, amount must not be presented in request, no payment will be made, only cardholder authentication will be performed. Also can be used to generate token. *(for BANKCARD payment method only)*
   * @return authenticationRequest
  **/
  @ApiModelProperty(value = "If set to `true`, amount must not be presented in request, no payment will be made, only cardholder authentication will be performed. Also can be used to generate token. *(for BANKCARD payment method only)*")
  public Boolean isAuthenticationRequest() {
    return authenticationRequest;
  }

  public void setAuthenticationRequest(Boolean authenticationRequest) {
    this.authenticationRequest = authenticationRequest;
  }

  public PaymentData created(String created) {
    this.created = created;
    return this;
  }

   /**
   * Time when this payment started in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format (yyyy-MM-dd&#39;T&#39;HH:mm:ss&#39;Z&#39;)
   * @return created
  **/
  @ApiModelProperty(value = "Time when this payment started in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format (yyyy-MM-dd'T'HH:mm:ss'Z')")
  public String getCreated() {
    return created;
  }

  public void setCreated(String created) {
    this.created = created;
  }

  public PaymentData currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code
   * @return currency
  **/
  @ApiModelProperty(example = "USD", required = true, value = "[ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public PaymentData declineCode(String declineCode) {
    this.declineCode = declineCode;
    return this;
  }

   /**
   * **Decline code** (only in decline case)
   * @return declineCode
  **/
  @ApiModelProperty(value = "**Decline code** (only in decline case)")
  public String getDeclineCode() {
    return declineCode;
  }

  public void setDeclineCode(String declineCode) {
    this.declineCode = declineCode;
  }

  public PaymentData declineReason(String declineReason) {
    this.declineReason = declineReason;
    return this;
  }

   /**
   * Bank&#39;s message about transaction decline reason (only in decline case)
   * @return declineReason
  **/
  @ApiModelProperty(value = "Bank's message about transaction decline reason (only in decline case)")
  public String getDeclineReason() {
    return declineReason;
  }

  public void setDeclineReason(String declineReason) {
    this.declineReason = declineReason;
  }

  public PaymentData dynamicDescriptor(String dynamicDescriptor) {
    this.dynamicDescriptor = dynamicDescriptor;
    return this;
  }

   /**
   * Short description of the service or product, must be enabled by CardPay manager to be used *(for BANKCARD payment method only)*
   * @return dynamicDescriptor
  **/
  @ApiModelProperty(value = "Short description of the service or product, must be enabled by CardPay manager to be used *(for BANKCARD payment method only)*")
  public String getDynamicDescriptor() {
    return dynamicDescriptor;
  }

  public void setDynamicDescriptor(String dynamicDescriptor) {
    this.dynamicDescriptor = dynamicDescriptor;
  }

  public PaymentData generateToken(Boolean generateToken) {
    this.generateToken = generateToken;
    return this;
  }

   /**
   * If set to &#x60;true&#x60;, token will be generated and returned in the response *(for BANKCARD payment method only)*
   * @return generateToken
  **/
  @ApiModelProperty(value = "If set to `true`, token will be generated and returned in the response *(for BANKCARD payment method only)*")
  public Boolean isGenerateToken() {
    return generateToken;
  }

  public void setGenerateToken(Boolean generateToken) {
    this.generateToken = generateToken;
  }

  public PaymentData id(String id) {
    this.id = id;
    return this;
  }

   /**
   * CardPay&#39;s payment id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "CardPay's payment id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PaymentData is3d(Boolean is3d) {
    this.is3d = is3d;
    return this;
  }

   /**
   * Was 3-D Secure authentication made or not *(for BANKCARD payment method only)*
   * @return is3d
  **/
  @ApiModelProperty(value = "Was 3-D Secure authentication made or not *(for BANKCARD payment method only)*")
  public Boolean isIs3d() {
    return is3d;
  }

  public void setIs3d(Boolean is3d) {
    this.is3d = is3d;
  }

  public PaymentData note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Note about the transaction that will not be displayed to customer
   * @return note
  **/
  @ApiModelProperty(value = "Note about the transaction that will not be displayed to customer")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public PaymentData preauth(Boolean preauth) {
    this.preauth = preauth;
    return this;
  }

   /**
   * If set to &#x60;true&#x60;, the amount will not be captured but only blocked *(for BANKCARD payment method only)*.
   * @return preauth
  **/
  @ApiModelProperty(value = "If set to `true`, the amount will not be captured but only blocked *(for BANKCARD payment method only)*.")
  public Boolean isPreauth() {
    return preauth;
  }

  public void setPreauth(Boolean preauth) {
    this.preauth = preauth;
  }

  public PaymentData rrn(String rrn) {
    this.rrn = rrn;
    return this;
  }

   /**
   * RRN (Retrieval Reference Number), supplied by the acquiring financial institution *(for BANKCARD payment method only)*
   * @return rrn
  **/
  @ApiModelProperty(value = "RRN (Retrieval Reference Number), supplied by the acquiring financial institution *(for BANKCARD payment method only)*")
  public String getRrn() {
    return rrn;
  }

  public void setRrn(String rrn) {
    this.rrn = rrn;
  }

  public PaymentData status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Current payment status, *(mandatory for WEBMONEY and BITCOIN payment method only)*
   * @return status
  **/
  @ApiModelProperty(value = "Current payment status, *(mandatory for WEBMONEY and BITCOIN payment method only)*")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentData paymentData = (PaymentData) o;
    return Objects.equals(this.amount, paymentData.amount) &&
        Objects.equals(this.authCode, paymentData.authCode) &&
        Objects.equals(this.authenticationRequest, paymentData.authenticationRequest) &&
        Objects.equals(this.created, paymentData.created) &&
        Objects.equals(this.currency, paymentData.currency) &&
        Objects.equals(this.declineCode, paymentData.declineCode) &&
        Objects.equals(this.declineReason, paymentData.declineReason) &&
        Objects.equals(this.dynamicDescriptor, paymentData.dynamicDescriptor) &&
        Objects.equals(this.generateToken, paymentData.generateToken) &&
        Objects.equals(this.id, paymentData.id) &&
        Objects.equals(this.is3d, paymentData.is3d) &&
        Objects.equals(this.note, paymentData.note) &&
        Objects.equals(this.preauth, paymentData.preauth) &&
        Objects.equals(this.rrn, paymentData.rrn) &&
        Objects.equals(this.status, paymentData.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, authCode, authenticationRequest, created, currency, declineCode, declineReason, dynamicDescriptor, generateToken, id, is3d, note, preauth, rrn, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentData {\n");
    
    if (amount != null) sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    if (authCode != null) sb.append("    authCode: ").append(toIndentedString(authCode)).append("\n");
    if (authenticationRequest != null) sb.append("    authenticationRequest: ").append(toIndentedString(authenticationRequest)).append("\n");
    if (created != null) sb.append("    created: ").append(toIndentedString(created)).append("\n");
    if (currency != null) sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    if (declineCode != null) sb.append("    declineCode: ").append(toIndentedString(declineCode)).append("\n");
    if (declineReason != null) sb.append("    declineReason: ").append(toIndentedString(declineReason)).append("\n");
    if (dynamicDescriptor != null) sb.append("    dynamicDescriptor: ").append(toIndentedString(dynamicDescriptor)).append("\n");
    if (generateToken != null) sb.append("    generateToken: ").append(toIndentedString(generateToken)).append("\n");
    if (id != null) sb.append("    id: ").append(toIndentedString(id)).append("\n");
    if (is3d != null) sb.append("    is3d: ").append(toIndentedString(is3d)).append("\n");
    if (note != null) sb.append("    note: ").append(toIndentedString(note)).append("\n");
    if (preauth != null) sb.append("    preauth: ").append(toIndentedString(preauth)).append("\n");
    if (rrn != null) sb.append("    rrn: ").append(toIndentedString(rrn)).append("\n");
    if (status != null) sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

