/*
 * CardPay REST API
 * The CardPay API uses HTTP verbs and a RESTful endpoint structure. Request and response payloads are formatted as JSON.
 *
 * OpenAPI spec version: 3.0
 * Contact: support@cardpay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.cardpay.sdk.model.CardAccount;
import com.cardpay.sdk.model.CryptocurrencyAccount;
import com.cardpay.sdk.model.Customer;
import com.cardpay.sdk.model.EWalletAccount;
import com.cardpay.sdk.model.MerchantOrder;
import com.cardpay.sdk.model.PaymentData;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PaymentResponse
 */

public class PaymentResponse {
  @SerializedName("payment_method")
  private String paymentMethod = null;

  @SerializedName("merchant_order")
  private MerchantOrder merchantOrder = null;

  @SerializedName("payment_data")
  private PaymentData paymentData = null;

  @SerializedName("card_account")
  private CardAccount cardAccount = null;

  @SerializedName("cryptocurrency_account")
  private CryptocurrencyAccount cryptocurrencyAccount = null;

  @SerializedName("ewallet_account")
  private EWalletAccount ewalletAccount = null;

  @SerializedName("customer")
  private Customer customer = null;

  public PaymentResponse paymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Used payment method type name from payment methods list
   * @return paymentMethod
  **/
  @ApiModelProperty(example = "BANKCARD", value = "Used payment method type name from payment methods list")
  public String getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public PaymentResponse merchantOrder(MerchantOrder merchantOrder) {
    this.merchantOrder = merchantOrder;
    return this;
  }

   /**
   * Merchant order data
   * @return merchantOrder
  **/
  @ApiModelProperty(value = "Merchant order data")
  public MerchantOrder getMerchantOrder() {
    return merchantOrder;
  }

  public void setMerchantOrder(MerchantOrder merchantOrder) {
    this.merchantOrder = merchantOrder;
  }

  public PaymentResponse paymentData(PaymentData paymentData) {
    this.paymentData = paymentData;
    return this;
  }

   /**
   * Payment data
   * @return paymentData
  **/
  @ApiModelProperty(value = "Payment data")
  public PaymentData getPaymentData() {
    return paymentData;
  }

  public void setPaymentData(PaymentData paymentData) {
    this.paymentData = paymentData;
  }

  public PaymentResponse cardAccount(CardAccount cardAccount) {
    this.cardAccount = cardAccount;
    return this;
  }

   /**
   * Card account data *(for BANKCARD payment method only)*
   * @return cardAccount
  **/
  @ApiModelProperty(value = "Card account data *(for BANKCARD payment method only)*")
  public CardAccount getCardAccount() {
    return cardAccount;
  }

  public void setCardAccount(CardAccount cardAccount) {
    this.cardAccount = cardAccount;
  }

  public PaymentResponse cryptocurrencyAccount(CryptocurrencyAccount cryptocurrencyAccount) {
    this.cryptocurrencyAccount = cryptocurrencyAccount;
    return this;
  }

   /**
   * Cryptocurrency account data *(for BITCOIN payment method only)*
   * @return cryptocurrencyAccount
  **/
  @ApiModelProperty(value = "Cryptocurrency account data *(for BITCOIN payment method only)*")
  public CryptocurrencyAccount getCryptocurrencyAccount() {
    return cryptocurrencyAccount;
  }

  public void setCryptocurrencyAccount(CryptocurrencyAccount cryptocurrencyAccount) {
    this.cryptocurrencyAccount = cryptocurrencyAccount;
  }

  public PaymentResponse ewalletAccount(EWalletAccount ewalletAccount) {
    this.ewalletAccount = ewalletAccount;
    return this;
  }

   /**
   * eWallet account data *(for ALIPAY, QIWI, WEBMONEY and NETELLER payment methods only)*
   * @return ewalletAccount
  **/
  @ApiModelProperty(value = "eWallet account data *(for ALIPAY, QIWI, WEBMONEY and NETELLER payment methods only)*")
  public EWalletAccount getEwalletAccount() {
    return ewalletAccount;
  }

  public void setEwalletAccount(EWalletAccount ewalletAccount) {
    this.ewalletAccount = ewalletAccount;
  }

  public PaymentResponse customer(Customer customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Customer data
   * @return customer
  **/
  @ApiModelProperty(value = "Customer data")
  public Customer getCustomer() {
    return customer;
  }

  public void setCustomer(Customer customer) {
    this.customer = customer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentResponse paymentResponse = (PaymentResponse) o;
    return Objects.equals(this.paymentMethod, paymentResponse.paymentMethod) &&
        Objects.equals(this.merchantOrder, paymentResponse.merchantOrder) &&
        Objects.equals(this.paymentData, paymentResponse.paymentData) &&
        Objects.equals(this.cardAccount, paymentResponse.cardAccount) &&
        Objects.equals(this.cryptocurrencyAccount, paymentResponse.cryptocurrencyAccount) &&
        Objects.equals(this.ewalletAccount, paymentResponse.ewalletAccount) &&
        Objects.equals(this.customer, paymentResponse.customer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentMethod, merchantOrder, paymentData, cardAccount, cryptocurrencyAccount, ewalletAccount, customer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentResponse {\n");
    
    if (paymentMethod != null) sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    if (merchantOrder != null) sb.append("    merchantOrder: ").append(toIndentedString(merchantOrder)).append("\n");
    if (paymentData != null) sb.append("    paymentData: ").append(toIndentedString(paymentData)).append("\n");
    if (cardAccount != null) sb.append("    cardAccount: ").append(toIndentedString(cardAccount)).append("\n");
    if (cryptocurrencyAccount != null) sb.append("    cryptocurrencyAccount: ").append(toIndentedString(cryptocurrencyAccount)).append("\n");
    if (ewalletAccount != null) sb.append("    ewalletAccount: ").append(toIndentedString(ewalletAccount)).append("\n");
    if (customer != null) sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

