/*
 * CardPay REST API
 * The CardPay API uses HTTP verbs and a RESTful endpoint structure. Request and response payloads are formatted as JSON.
 *
 * OpenAPI spec version: 3.0
 * Contact: support@cardpay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.cardpay.sdk.model.Request;
import com.cardpay.sdk.model.UpdatePlanData;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PlanUpdateRequest
 */

public class PlanUpdateRequest {
  @SerializedName("request")
  private Request request = null;

  /**
   * &#x60;CHANGE_STATUS&#x60; value to initiate operation for status changing. &#x60;RENAME&#x60; value to initiate operation for plan renaming.
   */
  @JsonAdapter(OperationEnum.Adapter.class)
  public enum OperationEnum {
    CHANGE_STATUS("CHANGE_STATUS"),
    
    RENAME("RENAME");

    private String value;

    OperationEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OperationEnum fromValue(String text) {
      for (OperationEnum b : OperationEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<OperationEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OperationEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OperationEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return OperationEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("operation")
  private OperationEnum operation = null;

  @SerializedName("plan_data")
  private UpdatePlanData planData = null;

  public PlanUpdateRequest request(Request request) {
    this.request = request;
    return this;
  }

   /**
   * Request
   * @return request
  **/
  @ApiModelProperty(required = true, value = "Request")
  public Request getRequest() {
    return request;
  }

  public void setRequest(Request request) {
    this.request = request;
  }

  public PlanUpdateRequest operation(OperationEnum operation) {
    this.operation = operation;
    return this;
  }

   /**
   * &#x60;CHANGE_STATUS&#x60; value to initiate operation for status changing. &#x60;RENAME&#x60; value to initiate operation for plan renaming.
   * @return operation
  **/
  @ApiModelProperty(required = true, value = "`CHANGE_STATUS` value to initiate operation for status changing. `RENAME` value to initiate operation for plan renaming.")
  public OperationEnum getOperation() {
    return operation;
  }

  public void setOperation(OperationEnum operation) {
    this.operation = operation;
  }

  public PlanUpdateRequest planData(UpdatePlanData planData) {
    this.planData = planData;
    return this;
  }

   /**
   * Plan data
   * @return planData
  **/
  @ApiModelProperty(required = true, value = "Plan data")
  public UpdatePlanData getPlanData() {
    return planData;
  }

  public void setPlanData(UpdatePlanData planData) {
    this.planData = planData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanUpdateRequest planUpdateRequest = (PlanUpdateRequest) o;
    return Objects.equals(this.request, planUpdateRequest.request) &&
        Objects.equals(this.operation, planUpdateRequest.operation) &&
        Objects.equals(this.planData, planUpdateRequest.planData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(request, operation, planData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanUpdateRequest {\n");
    
    if (request != null) sb.append("    request: ").append(toIndentedString(request)).append("\n");
    if (operation != null) sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    if (planData != null) sb.append("    planData: ").append(toIndentedString(planData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

