/*
 * CardPay REST API
 * The CardPay API uses HTTP verbs and a RESTful endpoint structure. Request and response payloads are formatted as JSON.
 *
 * OpenAPI spec version: 3.0
 * Contact: support@cardpay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Using for RecurringPlanRequest
 */
@ApiModel(description = "Using for RecurringPlanRequest")

public class PlanData {
  @SerializedName("amount")
  private BigDecimal amount = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("interval")
  private Integer interval = null;

  @SerializedName("name")
  private String name = null;

  /**
   * Initial period of recurring, can be &#x60;day&#x60;, &#x60;week&#x60;, &#x60;month&#x60;, &#x60;year&#x60;
   */
  @JsonAdapter(PeriodEnum.Adapter.class)
  public enum PeriodEnum {
    MINUTE("minute"),
    
    DAY("day"),
    
    WEEK("week"),
    
    MONTH("month"),
    
    YEAR("year");

    private String value;

    PeriodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PeriodEnum fromValue(String text) {
      for (PeriodEnum b : PeriodEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<PeriodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PeriodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PeriodEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return PeriodEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("period")
  private PeriodEnum period = null;

  @SerializedName("retries")
  private Integer retries = null;

  public PlanData amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * The amount charged per period defined in plan in selected currency with dot as a decimal separator, limit is defined by payment method and transaction details.
   * @return amount
  **/
  @ApiModelProperty(required = true, value = "The amount charged per period defined in plan in selected currency with dot as a decimal separator, limit is defined by payment method and transaction details.")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public PlanData currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code of plan
   * @return currency
  **/
  @ApiModelProperty(example = "USD", required = true, value = "[ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code of plan")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public PlanData interval(Integer interval) {
    this.interval = interval;
    return this;
  }

   /**
   * The frequency interval of period, can be 1-365 depending on selected period value. Maximum total value of period + interval can be 365 days / 52 weeks / 12 months / 1 year
   * minimum: 1
   * @return interval
  **/
  @ApiModelProperty(required = true, value = "The frequency interval of period, can be 1-365 depending on selected period value. Maximum total value of period + interval can be 365 days / 52 weeks / 12 months / 1 year")
  public Integer getInterval() {
    return interval;
  }

  public void setInterval(Integer interval) {
    this.interval = interval;
  }

  public PlanData name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Plan name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Plan name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PlanData period(PeriodEnum period) {
    this.period = period;
    return this;
  }

   /**
   * Initial period of recurring, can be &#x60;day&#x60;, &#x60;week&#x60;, &#x60;month&#x60;, &#x60;year&#x60;
   * @return period
  **/
  @ApiModelProperty(required = true, value = "Initial period of recurring, can be `day`, `week`, `month`, `year`")
  public PeriodEnum getPeriod() {
    return period;
  }

  public void setPeriod(PeriodEnum period) {
    this.period = period;
  }

  public PlanData retries(Integer retries) {
    this.retries = retries;
    return this;
  }

   /**
   * Number of daily basis retry attempts in case of payment has not been captured
   * minimum: 1
   * maximum: 15
   * @return retries
  **/
  @ApiModelProperty(value = "Number of daily basis retry attempts in case of payment has not been captured")
  public Integer getRetries() {
    return retries;
  }

  public void setRetries(Integer retries) {
    this.retries = retries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanData planData = (PlanData) o;
    return Objects.equals(this.amount, planData.amount) &&
        Objects.equals(this.currency, planData.currency) &&
        Objects.equals(this.interval, planData.interval) &&
        Objects.equals(this.name, planData.name) &&
        Objects.equals(this.period, planData.period) &&
        Objects.equals(this.retries, planData.retries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, currency, interval, name, period, retries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanData {\n");
    
    if (amount != null) sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    if (currency != null) sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    if (interval != null) sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    if (name != null) sb.append("    name: ").append(toIndentedString(name)).append("\n");
    if (period != null) sb.append("    period: ").append(toIndentedString(period)).append("\n");
    if (retries != null) sb.append("    retries: ").append(toIndentedString(retries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

