/*
 * CardPay REST API
 * The CardPay API uses HTTP verbs and a RESTful endpoint structure. Request and response payloads are formatted as JSON.
 *
 * OpenAPI spec version: 3.0
 * Contact: support@cardpay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.cardpay.sdk.model.CardAccount;
import com.cardpay.sdk.model.Customer;
import com.cardpay.sdk.model.MerchantOrder;
import com.cardpay.sdk.model.ResponseUpdatedTransactionData;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ## Fields for &#x60;CHANGE_STATUS&#x60; operation * operation * merchant_data * recurring_data ## Fields for &#x60;CONFIRM_3DS&#x60; operation * payment_method * merchant_data * recurring_data * card_account * customer  
 */
@ApiModel(description = "## Fields for `CHANGE_STATUS` operation * operation * merchant_data * recurring_data ## Fields for `CONFIRM_3DS` operation * payment_method * merchant_data * recurring_data * card_account * customer  ")

public class RecurringUpdateResponse {
  /**
   * &#x60;CHANGE_STATUS&#x60; value
   */
  @JsonAdapter(OperationEnum.Adapter.class)
  public enum OperationEnum {
    CHANGE_STATUS("CHANGE_STATUS"),
    
    CONFIRM_3DS("CONFIRM_3DS");

    private String value;

    OperationEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OperationEnum fromValue(String text) {
      for (OperationEnum b : OperationEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<OperationEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OperationEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OperationEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return OperationEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("operation")
  private OperationEnum operation = null;

  @SerializedName("payment_method")
  private String paymentMethod = null;

  @SerializedName("merchant_data")
  private MerchantOrder merchantData = null;

  @SerializedName("recurring_data")
  private ResponseUpdatedTransactionData recurringData = null;

  @SerializedName("card_account")
  private CardAccount cardAccount = null;

  @SerializedName("customer")
  private Customer customer = null;

  public RecurringUpdateResponse operation(OperationEnum operation) {
    this.operation = operation;
    return this;
  }

   /**
   * &#x60;CHANGE_STATUS&#x60; value
   * @return operation
  **/
  @ApiModelProperty(value = "`CHANGE_STATUS` value")
  public OperationEnum getOperation() {
    return operation;
  }

  public void setOperation(OperationEnum operation) {
    this.operation = operation;
  }

  public RecurringUpdateResponse paymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Used payment method type name from payment methods list
   * @return paymentMethod
  **/
  @ApiModelProperty(example = "BANKCARD", value = "Used payment method type name from payment methods list")
  public String getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public RecurringUpdateResponse merchantData(MerchantOrder merchantData) {
    this.merchantData = merchantData;
    return this;
  }

   /**
   * Get merchantData
   * @return merchantData
  **/
  @ApiModelProperty(value = "")
  public MerchantOrder getMerchantData() {
    return merchantData;
  }

  public void setMerchantData(MerchantOrder merchantData) {
    this.merchantData = merchantData;
  }

  public RecurringUpdateResponse recurringData(ResponseUpdatedTransactionData recurringData) {
    this.recurringData = recurringData;
    return this;
  }

   /**
   * Get recurringData
   * @return recurringData
  **/
  @ApiModelProperty(value = "")
  public ResponseUpdatedTransactionData getRecurringData() {
    return recurringData;
  }

  public void setRecurringData(ResponseUpdatedTransactionData recurringData) {
    this.recurringData = recurringData;
  }

  public RecurringUpdateResponse cardAccount(CardAccount cardAccount) {
    this.cardAccount = cardAccount;
    return this;
  }

   /**
   * Get cardAccount
   * @return cardAccount
  **/
  @ApiModelProperty(value = "")
  public CardAccount getCardAccount() {
    return cardAccount;
  }

  public void setCardAccount(CardAccount cardAccount) {
    this.cardAccount = cardAccount;
  }

  public RecurringUpdateResponse customer(Customer customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Customer data
   * @return customer
  **/
  @ApiModelProperty(value = "Customer data")
  public Customer getCustomer() {
    return customer;
  }

  public void setCustomer(Customer customer) {
    this.customer = customer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecurringUpdateResponse recurringUpdateResponse = (RecurringUpdateResponse) o;
    return Objects.equals(this.operation, recurringUpdateResponse.operation) &&
        Objects.equals(this.paymentMethod, recurringUpdateResponse.paymentMethod) &&
        Objects.equals(this.merchantData, recurringUpdateResponse.merchantData) &&
        Objects.equals(this.recurringData, recurringUpdateResponse.recurringData) &&
        Objects.equals(this.cardAccount, recurringUpdateResponse.cardAccount) &&
        Objects.equals(this.customer, recurringUpdateResponse.customer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operation, paymentMethod, merchantData, recurringData, cardAccount, customer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecurringUpdateResponse {\n");
    
    if (operation != null) sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    if (paymentMethod != null) sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    if (merchantData != null) sb.append("    merchantData: ").append(toIndentedString(merchantData)).append("\n");
    if (recurringData != null) sb.append("    recurringData: ").append(toIndentedString(recurringData)).append("\n");
    if (cardAccount != null) sb.append("    cardAccount: ").append(toIndentedString(cardAccount)).append("\n");
    if (customer != null) sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

