/*
 * CardPay REST API
 * The CardPay API uses HTTP verbs and a RESTful endpoint structure. Request and response payloads are formatted as JSON.
 *
 * OpenAPI spec version: 3.0
 * Contact: support@cardpay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.cardpay.sdk.model.RefundData;
import com.cardpay.sdk.model.RefundMerchantOrder;
import com.cardpay.sdk.model.RefundPaymentData;
import com.cardpay.sdk.model.Request;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RefundRequest
 */

public class RefundRequest {
  @SerializedName("request")
  private Request request = null;

  @SerializedName("merchant_order")
  private RefundMerchantOrder merchantOrder = null;

  @SerializedName("payment_data")
  private RefundPaymentData paymentData = null;

  @SerializedName("refund_data")
  private RefundData refundData = null;

  public RefundRequest request(Request request) {
    this.request = request;
    return this;
  }

   /**
   * Request
   * @return request
  **/
  @ApiModelProperty(required = true, value = "Request")
  public Request getRequest() {
    return request;
  }

  public void setRequest(Request request) {
    this.request = request;
  }

  public RefundRequest merchantOrder(RefundMerchantOrder merchantOrder) {
    this.merchantOrder = merchantOrder;
    return this;
  }

   /**
   * Merchant order data
   * @return merchantOrder
  **/
  @ApiModelProperty(value = "Merchant order data")
  public RefundMerchantOrder getMerchantOrder() {
    return merchantOrder;
  }

  public void setMerchantOrder(RefundMerchantOrder merchantOrder) {
    this.merchantOrder = merchantOrder;
  }

  public RefundRequest paymentData(RefundPaymentData paymentData) {
    this.paymentData = paymentData;
    return this;
  }

   /**
   * Payment data
   * @return paymentData
  **/
  @ApiModelProperty(required = true, value = "Payment data")
  public RefundPaymentData getPaymentData() {
    return paymentData;
  }

  public void setPaymentData(RefundPaymentData paymentData) {
    this.paymentData = paymentData;
  }

  public RefundRequest refundData(RefundData refundData) {
    this.refundData = refundData;
    return this;
  }

   /**
   * Refund data
   * @return refundData
  **/
  @ApiModelProperty(value = "Refund data")
  public RefundData getRefundData() {
    return refundData;
  }

  public void setRefundData(RefundData refundData) {
    this.refundData = refundData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefundRequest refundRequest = (RefundRequest) o;
    return Objects.equals(this.request, refundRequest.request) &&
        Objects.equals(this.merchantOrder, refundRequest.merchantOrder) &&
        Objects.equals(this.paymentData, refundRequest.paymentData) &&
        Objects.equals(this.refundData, refundRequest.refundData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(request, merchantOrder, paymentData, refundData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefundRequest {\n");
    
    if (request != null) sb.append("    request: ").append(toIndentedString(request)).append("\n");
    if (merchantOrder != null) sb.append("    merchantOrder: ").append(toIndentedString(merchantOrder)).append("\n");
    if (paymentData != null) sb.append("    paymentData: ").append(toIndentedString(paymentData)).append("\n");
    if (refundData != null) sb.append("    refundData: ").append(toIndentedString(refundData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

