/*
 * CardPay REST API
 * The CardPay API uses HTTP verbs and a RESTful endpoint structure. Request and response payloads are formatted as JSON.
 *
 * OpenAPI spec version: 3.0
 * Contact: support@cardpay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Using for RefundResponse
 */
@ApiModel(description = "Using for RefundResponse")

public class RefundPaymentData {
  @SerializedName("id")
  private String id = null;

  @SerializedName("remaining_amount")
  private BigDecimal remainingAmount = null;

  public RefundPaymentData id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id of refunded or partial refunded payment
   * @return id
  **/
  @ApiModelProperty(example = "373278232", required = true, value = "Id of refunded or partial refunded payment")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RefundPaymentData remainingAmount(BigDecimal remainingAmount) {
    this.remainingAmount = remainingAmount;
    return this;
  }

   /**
   * Payment amount left after refund was made
   * @return remainingAmount
  **/
  @ApiModelProperty(example = "10.43", required = true, value = "Payment amount left after refund was made")
  public BigDecimal getRemainingAmount() {
    return remainingAmount;
  }

  public void setRemainingAmount(BigDecimal remainingAmount) {
    this.remainingAmount = remainingAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefundPaymentData refundPaymentData = (RefundPaymentData) o;
    return Objects.equals(this.id, refundPaymentData.id) &&
        Objects.equals(this.remainingAmount, refundPaymentData.remainingAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, remainingAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefundPaymentData {\n");
    
    if (id != null) sb.append("    id: ").append(toIndentedString(id)).append("\n");
    if (remainingAmount != null) sb.append("    remainingAmount: ").append(toIndentedString(remainingAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

