/*
 * CardPay REST API
 * The CardPay API uses HTTP verbs and a RESTful endpoint structure. Request and response payloads are formatted as JSON.
 *
 * OpenAPI spec version: 3.0
 * Contact: support@cardpay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.cardpay.sdk.model.EWalletAccount;
import com.cardpay.sdk.model.MerchantOrder;
import com.cardpay.sdk.model.RefundCardAccount;
import com.cardpay.sdk.model.RefundCustomer;
import com.cardpay.sdk.model.RefundPaymentData;
import com.cardpay.sdk.model.ResponseRefundData;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RefundResponse
 */

public class RefundResponse {
  @SerializedName("card_account")
  private RefundCardAccount cardAccount = null;

  @SerializedName("customer")
  private RefundCustomer customer = null;

  @SerializedName("ewallet_account")
  private EWalletAccount ewalletAccount = null;

  @SerializedName("payment_data")
  private RefundPaymentData paymentData = null;

  @SerializedName("refund_data")
  private ResponseRefundData refundData = null;

  @SerializedName("payment_method")
  private String paymentMethod = null;

  @SerializedName("merchant_order")
  private MerchantOrder merchantOrder = null;

  public RefundResponse cardAccount(RefundCardAccount cardAccount) {
    this.cardAccount = cardAccount;
    return this;
  }

   /**
   * Card account data *(for BANKCARD payment method only)*
   * @return cardAccount
  **/
  @ApiModelProperty(value = "Card account data *(for BANKCARD payment method only)*")
  public RefundCardAccount getCardAccount() {
    return cardAccount;
  }

  public void setCardAccount(RefundCardAccount cardAccount) {
    this.cardAccount = cardAccount;
  }

  public RefundResponse customer(RefundCustomer customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Customer data
   * @return customer
  **/
  @ApiModelProperty(value = "Customer data")
  public RefundCustomer getCustomer() {
    return customer;
  }

  public void setCustomer(RefundCustomer customer) {
    this.customer = customer;
  }

  public RefundResponse ewalletAccount(EWalletAccount ewalletAccount) {
    this.ewalletAccount = ewalletAccount;
    return this;
  }

   /**
   * eWallet account data *(for QIWI and ALIPAY payment methods only)*
   * @return ewalletAccount
  **/
  @ApiModelProperty(value = "eWallet account data *(for QIWI and ALIPAY payment methods only)*")
  public EWalletAccount getEwalletAccount() {
    return ewalletAccount;
  }

  public void setEwalletAccount(EWalletAccount ewalletAccount) {
    this.ewalletAccount = ewalletAccount;
  }

  public RefundResponse paymentData(RefundPaymentData paymentData) {
    this.paymentData = paymentData;
    return this;
  }

   /**
   * Payment data
   * @return paymentData
  **/
  @ApiModelProperty(required = true, value = "Payment data")
  public RefundPaymentData getPaymentData() {
    return paymentData;
  }

  public void setPaymentData(RefundPaymentData paymentData) {
    this.paymentData = paymentData;
  }

  public RefundResponse refundData(ResponseRefundData refundData) {
    this.refundData = refundData;
    return this;
  }

   /**
   * Refund data
   * @return refundData
  **/
  @ApiModelProperty(required = true, value = "Refund data")
  public ResponseRefundData getRefundData() {
    return refundData;
  }

  public void setRefundData(ResponseRefundData refundData) {
    this.refundData = refundData;
  }

  public RefundResponse paymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Used payment method type name from payment methods list
   * @return paymentMethod
  **/
  @ApiModelProperty(example = "BANKCARD", value = "Used payment method type name from payment methods list")
  public String getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public RefundResponse merchantOrder(MerchantOrder merchantOrder) {
    this.merchantOrder = merchantOrder;
    return this;
  }

   /**
   * Merchant order data
   * @return merchantOrder
  **/
  @ApiModelProperty(value = "Merchant order data")
  public MerchantOrder getMerchantOrder() {
    return merchantOrder;
  }

  public void setMerchantOrder(MerchantOrder merchantOrder) {
    this.merchantOrder = merchantOrder;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefundResponse refundResponse = (RefundResponse) o;
    return Objects.equals(this.cardAccount, refundResponse.cardAccount) &&
        Objects.equals(this.customer, refundResponse.customer) &&
        Objects.equals(this.ewalletAccount, refundResponse.ewalletAccount) &&
        Objects.equals(this.paymentData, refundResponse.paymentData) &&
        Objects.equals(this.refundData, refundResponse.refundData) &&
        Objects.equals(this.paymentMethod, refundResponse.paymentMethod) &&
        Objects.equals(this.merchantOrder, refundResponse.merchantOrder);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardAccount, customer, ewalletAccount, paymentData, refundData, paymentMethod, merchantOrder);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefundResponse {\n");
    
    if (cardAccount != null) sb.append("    cardAccount: ").append(toIndentedString(cardAccount)).append("\n");
    if (customer != null) sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    if (ewalletAccount != null) sb.append("    ewalletAccount: ").append(toIndentedString(ewalletAccount)).append("\n");
    if (paymentData != null) sb.append("    paymentData: ").append(toIndentedString(paymentData)).append("\n");
    if (refundData != null) sb.append("    refundData: ").append(toIndentedString(refundData)).append("\n");
    if (paymentMethod != null) sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    if (merchantOrder != null) sb.append("    merchantOrder: ").append(toIndentedString(merchantOrder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

