/*
 * CardPay REST API
 * The CardPay API uses HTTP verbs and a RESTful endpoint structure. Request and response payloads are formatted as JSON.
 *
 * OpenAPI spec version: 3.0
 * Contact: support@cardpay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.cardpay.sdk.model.ResponseFiling;
import com.cardpay.sdk.model.Subscription;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * For BANKCARD payment method only. Using for RecurringResponse
 */
@ApiModel(description = "For BANKCARD payment method only. Using for RecurringResponse")

public class ResponseRecurringData {
  @SerializedName("amount")
  private BigDecimal amount = null;

  @SerializedName("auth_code")
  private String authCode = null;

  @SerializedName("created")
  private String created = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("decline_code")
  private String declineCode = null;

  @SerializedName("decline_reason")
  private String declineReason = null;

  @SerializedName("filing")
  private ResponseFiling filing = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("is_3d")
  private Boolean is3d = null;

  @SerializedName("note")
  private String note = null;

  @SerializedName("rrn")
  private String rrn = null;

  /**
   * Current recurring payment **status**
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    NEW("NEW"),
    
    IN_PROGRESS("IN_PROGRESS"),
    
    DECLINED("DECLINED"),
    
    AUTHORIZED("AUTHORIZED"),
    
    COMPLETED("COMPLETED"),
    
    CANCELLED("CANCELLED"),
    
    REFUNDED("REFUNDED"),
    
    PARTIALLY_REFUNDED("PARTIALLY_REFUNDED"),
    
    VOIDED("VOIDED"),
    
    CHARGED_BACK("CHARGED_BACK"),
    
    CHARGEBACK_RESOLVED("CHARGEBACK_RESOLVED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("subscription")
  private Subscription subscription = null;

  /**
   * Recurring payment type name; can be ONECLICK, SCHEDULED, INSTALLMENT
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    ONECLICK("ONECLICK"),
    
    SCHEDULED("SCHEDULED"),
    
    INSTALLMENT("INSTALLMENT");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  public ResponseRecurringData amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Recurring amount
   * @return amount
  **/
  @ApiModelProperty(required = true, value = "Recurring amount")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public ResponseRecurringData authCode(String authCode) {
    this.authCode = authCode;
    return this;
  }

   /**
   * Authorization code, provided by bank
   * @return authCode
  **/
  @ApiModelProperty(value = "Authorization code, provided by bank")
  public String getAuthCode() {
    return authCode;
  }

  public void setAuthCode(String authCode) {
    this.authCode = authCode;
  }

  public ResponseRecurringData created(String created) {
    this.created = created;
    return this;
  }

   /**
   * Date and time when this recurring payment created, up to milliseconds, [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format (yyyy-MM-dd&#39;T&#39;HH:mm:ss&#39;Z&#39;)
   * @return created
  **/
  @ApiModelProperty(required = true, value = "Date and time when this recurring payment created, up to milliseconds, [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format (yyyy-MM-dd'T'HH:mm:ss'Z')")
  public String getCreated() {
    return created;
  }

  public void setCreated(String created) {
    this.created = created;
  }

  public ResponseRecurringData currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Recurring currency code ([ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) code
   * @return currency
  **/
  @ApiModelProperty(required = true, value = "Recurring currency code ([ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) code")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public ResponseRecurringData declineCode(String declineCode) {
    this.declineCode = declineCode;
    return this;
  }

   /**
   * **Decline code** (only in decline case)
   * @return declineCode
  **/
  @ApiModelProperty(value = "**Decline code** (only in decline case)")
  public String getDeclineCode() {
    return declineCode;
  }

  public void setDeclineCode(String declineCode) {
    this.declineCode = declineCode;
  }

  public ResponseRecurringData declineReason(String declineReason) {
    this.declineReason = declineReason;
    return this;
  }

   /**
   * Bank&#39;s message about transaction decline reason (only in decline case)
   * @return declineReason
  **/
  @ApiModelProperty(value = "Bank's message about transaction decline reason (only in decline case)")
  public String getDeclineReason() {
    return declineReason;
  }

  public void setDeclineReason(String declineReason) {
    this.declineReason = declineReason;
  }

  public ResponseRecurringData filing(ResponseFiling filing) {
    this.filing = filing;
    return this;
  }

   /**
   * CardPay&#39;s filing data
   * @return filing
  **/
  @ApiModelProperty(value = "CardPay's filing data")
  public ResponseFiling getFiling() {
    return filing;
  }

  public void setFiling(ResponseFiling filing) {
    this.filing = filing;
  }

  public ResponseRecurringData id(String id) {
    this.id = id;
    return this;
  }

   /**
   * CardPay&#39;s recurring id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "CardPay's recurring id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ResponseRecurringData is3d(Boolean is3d) {
    this.is3d = is3d;
    return this;
  }

   /**
   * Was 3-D Secure authentication made or not
   * @return is3d
  **/
  @ApiModelProperty(value = "Was 3-D Secure authentication made or not")
  public Boolean isIs3d() {
    return is3d;
  }

  public void setIs3d(Boolean is3d) {
    this.is3d = is3d;
  }

  public ResponseRecurringData note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Payment note
   * @return note
  **/
  @ApiModelProperty(value = "Payment note")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public ResponseRecurringData rrn(String rrn) {
    this.rrn = rrn;
    return this;
  }

   /**
   * RRN (Retrieval Reference Number), supplied by the acquiring financial institution
   * @return rrn
  **/
  @ApiModelProperty(value = "RRN (Retrieval Reference Number), supplied by the acquiring financial institution")
  public String getRrn() {
    return rrn;
  }

  public void setRrn(String rrn) {
    this.rrn = rrn;
  }

  public ResponseRecurringData status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Current recurring payment **status**
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Current recurring payment **status**")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public ResponseRecurringData subscription(Subscription subscription) {
    this.subscription = subscription;
    return this;
  }

   /**
   * Subscription data
   * @return subscription
  **/
  @ApiModelProperty(value = "Subscription data")
  public Subscription getSubscription() {
    return subscription;
  }

  public void setSubscription(Subscription subscription) {
    this.subscription = subscription;
  }

  public ResponseRecurringData type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Recurring payment type name; can be ONECLICK, SCHEDULED, INSTALLMENT
   * @return type
  **/
  @ApiModelProperty(value = "Recurring payment type name; can be ONECLICK, SCHEDULED, INSTALLMENT")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRecurringData responseRecurringData = (ResponseRecurringData) o;
    return Objects.equals(this.amount, responseRecurringData.amount) &&
        Objects.equals(this.authCode, responseRecurringData.authCode) &&
        Objects.equals(this.created, responseRecurringData.created) &&
        Objects.equals(this.currency, responseRecurringData.currency) &&
        Objects.equals(this.declineCode, responseRecurringData.declineCode) &&
        Objects.equals(this.declineReason, responseRecurringData.declineReason) &&
        Objects.equals(this.filing, responseRecurringData.filing) &&
        Objects.equals(this.id, responseRecurringData.id) &&
        Objects.equals(this.is3d, responseRecurringData.is3d) &&
        Objects.equals(this.note, responseRecurringData.note) &&
        Objects.equals(this.rrn, responseRecurringData.rrn) &&
        Objects.equals(this.status, responseRecurringData.status) &&
        Objects.equals(this.subscription, responseRecurringData.subscription) &&
        Objects.equals(this.type, responseRecurringData.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, authCode, created, currency, declineCode, declineReason, filing, id, is3d, note, rrn, status, subscription, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRecurringData {\n");
    
    if (amount != null) sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    if (authCode != null) sb.append("    authCode: ").append(toIndentedString(authCode)).append("\n");
    if (created != null) sb.append("    created: ").append(toIndentedString(created)).append("\n");
    if (currency != null) sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    if (declineCode != null) sb.append("    declineCode: ").append(toIndentedString(declineCode)).append("\n");
    if (declineReason != null) sb.append("    declineReason: ").append(toIndentedString(declineReason)).append("\n");
    if (filing != null) sb.append("    filing: ").append(toIndentedString(filing)).append("\n");
    if (id != null) sb.append("    id: ").append(toIndentedString(id)).append("\n");
    if (is3d != null) sb.append("    is3d: ").append(toIndentedString(is3d)).append("\n");
    if (note != null) sb.append("    note: ").append(toIndentedString(note)).append("\n");
    if (rrn != null) sb.append("    rrn: ").append(toIndentedString(rrn)).append("\n");
    if (status != null) sb.append("    status: ").append(toIndentedString(status)).append("\n");
    if (subscription != null) sb.append("    subscription: ").append(toIndentedString(subscription)).append("\n");
    if (type != null) sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

