/*
 * CardPay REST API
 * The CardPay API uses HTTP verbs and a RESTful endpoint structure. Request and response payloads are formatted as JSON.
 *
 * OpenAPI spec version: 3.0
 * Contact: support@cardpay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.cardpay.sdk.model.PlanDataforUpdatedSubscriptionData;
import com.cardpay.sdk.model.ResponseFiling;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * Using for SubscriptionUpdateResponse
 */
@ApiModel(description = "Using for SubscriptionUpdateResponse")

public class UpdatedSubscriptionData {
  @SerializedName("change_status_claim_id")
  private String changeStatusClaimId = null;

  @SerializedName("filing")
  private ResponseFiling filing = null;

  @SerializedName("payment_data")
  private PlanDataforUpdatedSubscriptionData paymentData = null;

  @SerializedName("remaining_amount")
  private BigDecimal remainingAmount = null;

  @SerializedName("id")
  private String id = null;

  /**
   * Requested action (status to be set)
   */
  @JsonAdapter(StatusToEnum.Adapter.class)
  public enum StatusToEnum {
    ACTIVE("ACTIVE"),
    
    INACTIVE("INACTIVE"),
    
    CANCELLED("CANCELLED"),
    
    PAST_DUE("PAST_DUE"),
    
    PENDING("PENDING"),
    
    COMPLETED("COMPLETED"),
    
    CARD_EXPIRED("CARD_EXPIRED");

    private String value;

    StatusToEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusToEnum fromValue(String text) {
      for (StatusToEnum b : StatusToEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusToEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusToEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusToEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusToEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status_to")
  private StatusToEnum statusTo = null;

  @SerializedName("is_executed")
  private Boolean isExecuted = null;

  @SerializedName("details")
  private String details = null;

  @SerializedName("updated")
  private OffsetDateTime updated = null;

  /**
   * Status of modified subscription (&#39;active&#39; or &#39;inactive&#39;)
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    
    INACTIVE("INACTIVE"),
    
    CANCELLED("CANCELLED"),
    
    PAST_DUE("PAST_DUE"),
    
    PENDING("PENDING"),
    
    COMPLETED("COMPLETED"),
    
    CARD_EXPIRED("CARD_EXPIRED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  public UpdatedSubscriptionData changeStatusClaimId(String changeStatusClaimId) {
    this.changeStatusClaimId = changeStatusClaimId;
    return this;
  }

   /**
   * Get changeStatusClaimId
   * @return changeStatusClaimId
  **/
  @ApiModelProperty(value = "")
  public String getChangeStatusClaimId() {
    return changeStatusClaimId;
  }

  public void setChangeStatusClaimId(String changeStatusClaimId) {
    this.changeStatusClaimId = changeStatusClaimId;
  }

  public UpdatedSubscriptionData filing(ResponseFiling filing) {
    this.filing = filing;
    return this;
  }

   /**
   * Get filing
   * @return filing
  **/
  @ApiModelProperty(value = "")
  public ResponseFiling getFiling() {
    return filing;
  }

  public void setFiling(ResponseFiling filing) {
    this.filing = filing;
  }

  public UpdatedSubscriptionData paymentData(PlanDataforUpdatedSubscriptionData paymentData) {
    this.paymentData = paymentData;
    return this;
  }

   /**
   * Get paymentData
   * @return paymentData
  **/
  @ApiModelProperty(value = "")
  public PlanDataforUpdatedSubscriptionData getPaymentData() {
    return paymentData;
  }

  public void setPaymentData(PlanDataforUpdatedSubscriptionData paymentData) {
    this.paymentData = paymentData;
  }

  public UpdatedSubscriptionData remainingAmount(BigDecimal remainingAmount) {
    this.remainingAmount = remainingAmount;
    return this;
  }

   /**
   * Get remainingAmount
   * @return remainingAmount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getRemainingAmount() {
    return remainingAmount;
  }

  public void setRemainingAmount(BigDecimal remainingAmount) {
    this.remainingAmount = remainingAmount;
  }

  public UpdatedSubscriptionData id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Represents the ID of the modified subscription
   * @return id
  **/
  @ApiModelProperty(value = "Represents the ID of the modified subscription")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public UpdatedSubscriptionData statusTo(StatusToEnum statusTo) {
    this.statusTo = statusTo;
    return this;
  }

   /**
   * Requested action (status to be set)
   * @return statusTo
  **/
  @ApiModelProperty(value = "Requested action (status to be set)")
  public StatusToEnum getStatusTo() {
    return statusTo;
  }

  public void setStatusTo(StatusToEnum statusTo) {
    this.statusTo = statusTo;
  }

  public UpdatedSubscriptionData isExecuted(Boolean isExecuted) {
    this.isExecuted = isExecuted;
    return this;
  }

   /**
   * Indicates was the request successful or not
   * @return isExecuted
  **/
  @ApiModelProperty(value = "Indicates was the request successful or not")
  public Boolean isIsExecuted() {
    return isExecuted;
  }

  public void setIsExecuted(Boolean isExecuted) {
    this.isExecuted = isExecuted;
  }

  public UpdatedSubscriptionData details(String details) {
    this.details = details;
    return this;
  }

   /**
   * The reason why request was unsuccessful
   * @return details
  **/
  @ApiModelProperty(value = "The reason why request was unsuccessful")
  public String getDetails() {
    return details;
  }

  public void setDetails(String details) {
    this.details = details;
  }

  public UpdatedSubscriptionData updated(OffsetDateTime updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Subscription update date
   * @return updated
  **/
  @ApiModelProperty(example = "2018-10-28T09:09:53Z", value = "Subscription update date")
  public OffsetDateTime getUpdated() {
    return updated;
  }

  public void setUpdated(OffsetDateTime updated) {
    this.updated = updated;
  }

  public UpdatedSubscriptionData status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Status of modified subscription (&#39;active&#39; or &#39;inactive&#39;)
   * @return status
  **/
  @ApiModelProperty(value = "Status of modified subscription ('active' or 'inactive')")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatedSubscriptionData updatedSubscriptionData = (UpdatedSubscriptionData) o;
    return Objects.equals(this.changeStatusClaimId, updatedSubscriptionData.changeStatusClaimId) &&
        Objects.equals(this.filing, updatedSubscriptionData.filing) &&
        Objects.equals(this.paymentData, updatedSubscriptionData.paymentData) &&
        Objects.equals(this.remainingAmount, updatedSubscriptionData.remainingAmount) &&
        Objects.equals(this.id, updatedSubscriptionData.id) &&
        Objects.equals(this.statusTo, updatedSubscriptionData.statusTo) &&
        Objects.equals(this.isExecuted, updatedSubscriptionData.isExecuted) &&
        Objects.equals(this.details, updatedSubscriptionData.details) &&
        Objects.equals(this.updated, updatedSubscriptionData.updated) &&
        Objects.equals(this.status, updatedSubscriptionData.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changeStatusClaimId, filing, paymentData, remainingAmount, id, statusTo, isExecuted, details, updated, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatedSubscriptionData {\n");
    
    if (changeStatusClaimId != null) sb.append("    changeStatusClaimId: ").append(toIndentedString(changeStatusClaimId)).append("\n");
    if (filing != null) sb.append("    filing: ").append(toIndentedString(filing)).append("\n");
    if (paymentData != null) sb.append("    paymentData: ").append(toIndentedString(paymentData)).append("\n");
    if (remainingAmount != null) sb.append("    remainingAmount: ").append(toIndentedString(remainingAmount)).append("\n");
    if (id != null) sb.append("    id: ").append(toIndentedString(id)).append("\n");
    if (statusTo != null) sb.append("    statusTo: ").append(toIndentedString(statusTo)).append("\n");
    if (isExecuted != null) sb.append("    isExecuted: ").append(toIndentedString(isExecuted)).append("\n");
    if (details != null) sb.append("    details: ").append(toIndentedString(details)).append("\n");
    if (updated != null) sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    if (status != null) sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

